/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge_conversor_moneda;

import com.conversor.currencyConverterUI;
import javax.swing.SwingUtilities;

public class App {
    public static void main(String[] args) {
        // CountryCurrencyAPI api = new CountryCurrencyAPI();
        // try {
        // api.callAPI();
        // // System.out.println(response);
        // } catch (Exception e) {
        // // TODO Auto-generated catch block
        // e.printStackTrace();
        // }
        SwingUtilities.invokeLater(() -> new currencyConverterUI().launchConverterUI());
    }
}
